# Generated by Django 5.2.6 on 2025-10-21 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_users', to='facilities.location'),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='accounts_au_user_id_96c97d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='accounts_au_timesta_276167_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='accounts_au_ip_addr_8bfa9d_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user'], name='ul_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['location'], name='ul_location_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together={('user', 'location')},
        ),
    ]
