# Generated by Django 5.2.6 on 2025-10-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_temporary_user_and_location_assignment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_exp_check_idx',
        ),
    ]
