# Generated by Django 5.2.6 on 2025-10-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_and_org_scoping'),
        ('accounts', '0003_remove_user_user_type_idx_and_more'),
    ]

    operations = [
    ]
