# Generated by Django 5.2.6 on 2025-10-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251016_1357'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='org_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='org_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_org_idx',
        ),
    ]
