# Generated by Django 5.2.6 on 2025-09-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_event_t_5077ff_idx',
            old_name='security_se_event_t_b9e9c4_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_timesta_684804_idx',
            old_name='security_se_timesta_9c0f8e_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_se_ip_addr_1ea45a_idx',
            old_name='security_se_ip_addr_7f8a9b_idx',
        ),
    ]
