# Generated by Django 5.2.6 on 2025-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['category__order', 'name']},
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.CharField(choices=[('page', 'Page Access'), ('action', 'Action/Button'), ('view', 'View Data'), ('edit', 'Edit Data'), ('delete', 'Delete Data')], max_length=20),
        ),
    ]
