# Generated by Django 5.2.6 on 2025-09-25 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('info', 'Information'), ('metrics', 'Metrics'), ('status', 'Status'), ('controls', 'Controls'), ('reports', 'Reports')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('field_schema', models.JSONField(default=dict, help_text='Field definitions for this section')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='facilities.location')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Actual data values for this section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.dashboardsection')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='facilities.locationdashboard')),
            ],
            options={
                'unique_together': {('dashboard', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('operating', 'Operating Permit'), ('environmental', 'Environmental Permit'), ('safety', 'Safety Permit'), ('construction', 'Construction Permit')], max_length=20)),
                ('permit_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('renewal_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='facilities.location')),
            ],
            options={
                'ordering': ['location', 'expiry_date'],
                'unique_together': {('location', 'permit_number')},
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tank_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('oil', 'Oil'), ('water', 'Water'), ('chemical', 'Chemical')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Capacity in gallons', max_digits=10)),
                ('current_level', models.DecimalField(decimal_places=2, default=0, help_text='Current level in gallons', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_inspection', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='facilities.location')),
            ],
            options={
                'ordering': ['location', 'name'],
                'unique_together': {('location', 'name')},
            },
        ),
    ]
