# Generated by Django 5.2.6 on 2025-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='facility_type',
            field=models.CharField(choices=[('gas_station', 'Gas Station'), ('truck_stop', 'Truck Stop'), ('storage_facility', 'Storage Facility'), ('distribution_center', 'Distribution Center'), ('terminal', 'Terminal'), ('convenience_store', 'Convenience Store')], default='gas_station', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
