# Generated by Django 5.2.6 on 2025-10-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_remove_location_address_location_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, max_length=50)),
                ('state_id_number', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('store_open_date', models.DateField(blank=True, null=True)),
                ('operational_region', models.CharField(blank=True, max_length=100)),
                ('tos_pos_date', models.DateField(blank=True, null=True)),
                ('gas_brand', models.CharField(default='Phillips', max_length=100)),
                ('store_operator_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('operational_district', models.CharField(blank=True, max_length=100)),
                ('lease_own', models.CharField(blank=True, max_length=50)),
                ('owner_id', models.CharField(blank=True, max_length=50)),
                ('tank_owner', models.CharField(blank=True, max_length=100)),
                ('tank_operator', models.CharField(blank=True, max_length=100)),
                ('num_ast', models.PositiveIntegerField(default=0)),
                ('num_ust_registered', models.PositiveIntegerField(default=0)),
                ('num_mpds', models.PositiveIntegerField(default=0)),
                ('insured', models.BooleanField(default=False)),
                ('remodel_close_date', models.DateField(blank=True, null=True)),
                ('remodel_open_date', models.DateField(blank=True, null=True)),
                ('reason_for_remodel', models.CharField(blank=True, max_length=200)),
                ('channel_of_trade', models.CharField(blank=True, max_length=100)),
                ('car_service_center', models.CharField(blank=True, max_length=100)),
                ('truck_service_center', models.CharField(blank=True, max_length=100)),
                ('bus_maintenance', models.CharField(blank=True, max_length=100)),
                ('defueling_site', models.CharField(blank=True, max_length=100)),
                ('defueling_method', models.CharField(blank=True, max_length=100)),
                ('compliance_manager_name', models.CharField(blank=True, max_length=100)),
                ('compliance_manager_phone', models.CharField(blank=True, max_length=20)),
                ('compliance_manager_email', models.EmailField(blank=True, max_length=254)),
                ('store_manager_name', models.CharField(blank=True, max_length=100)),
                ('store_manager_phone', models.CharField(blank=True, max_length=20)),
                ('store_manager_email', models.EmailField(blank=True, max_length=254)),
                ('testing_vendor_name', models.CharField(blank=True, max_length=100)),
                ('testing_vendor_phone', models.CharField(blank=True, max_length=20)),
                ('testing_vendor_email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['location', 'label']},
        ),
        migrations.AlterUniqueTogether(
            name='tank',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tank',
            name='atg_id',
            field=models.CharField(blank=True, help_text='ATG system identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='tank',
            name='compartment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='tank',
            name='installed',
            field=models.CharField(blank=True, help_text='Installation date', max_length=20),
        ),
        migrations.AddField(
            model_name='tank',
            name='label',
            field=models.CharField(default='Unlabeled', help_text='Tank identifier/label', max_length=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='manifolded_with',
            field=models.CharField(blank=True, help_text='Other tanks this is manifolded with', max_length=200),
        ),
        migrations.AddField(
            model_name='tank',
            name='piping_detection',
            field=models.CharField(blank=True, help_text='Piping detection method', max_length=200),
        ),
        migrations.AddField(
            model_name='tank',
            name='piping_installed',
            field=models.CharField(blank=True, help_text='Piping installation date', max_length=20),
        ),
        migrations.AddField(
            model_name='tank',
            name='piping_manifolded_with',
            field=models.CharField(blank=True, help_text='Piping manifold connections', max_length=200),
        ),
        migrations.AddField(
            model_name='tank',
            name='piping_material',
            field=models.CharField(blank=True, help_text='Piping material', max_length=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='product',
            field=models.CharField(blank=True, help_text='Product stored in tank', max_length=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='release_detection',
            field=models.CharField(blank=True, help_text='Release detection method', max_length=200),
        ),
        migrations.AddField(
            model_name='tank',
            name='size',
            field=models.CharField(blank=True, help_text='Tank size/capacity', max_length=50),
        ),
        migrations.AddField(
            model_name='tank',
            name='stp_sumps',
            field=models.CharField(blank=True, help_text='STP sumps information', max_length=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='tank_lined',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='tank',
            name='tank_material',
            field=models.CharField(blank=True, help_text='Tank construction material', max_length=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='track_release_detection',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='tank',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tank',
            constraint=models.UniqueConstraint(fields=('location', 'label'), name='uniq_location_label'),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='facilities.location'),
        ),
        migrations.RemoveField(
            model_name='tank',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='last_inspection',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='material',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='tank_type',
        ),
    ]
